name: Snap

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  snap-build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: canonical/action-build@v1
